for upload readme wasabi
pli888/gigadb-website pull request #38
Opened 2023-08-08 07:21 UTC by kencho51

# Pull request for issue: #<insert relevant github issue numbers that this PR is related to>

This is a pull request for the following functionalities:

* Describe functionality 1
* Describe functionality 2
* *Etc.*

## How to test?

Describe how the new functionalities can be tested by PR reviewers

## How have functionalities been implemented?

Describe how the new functionalities have been implemented by the
changed code at a high level

## Any issues with implementation?

Describe any problems with your implementation

## Any changes to automated tests?

Describe any automated tests that have been developed for the new 
functionalities

## Any changes to documentation?

Describe changes to the documentation

## Any technical debt repayment?

Describe changes to code that repays any technical debt

## Any improvements to CI/CD pipeline?

Describe any improvements to the Gitlab pipeline

2023-08-14 18:34 UTC, rija requested changes
Hi @kencho51,

Testing your changes to @pli888's PR, here are some initial feedback:

**praise**: got the tool working on local dev and AWS staging as instructed without errors
**issue**: production containers must be immutable, otherwise we cannot guarantee which version of the code is running on production at any given time
**suggestion**: don't mount volumes for code or configuration  in the production docker-compose (mounting files that are generated on the running environment is fine). 
If some files/directories are missing they need to be copied from the build environment during the build stage by adding COPY directives inside the Production Dockerfile (look at all the other projects, like file-metadata-console as examples)

2023-08-15 08:15 UTC, kencho51 commented
Hi @rija,

> don't mount volumes for code or configuration in the production docker-compose

The volume has been removed. Initially, if there is no mounting, it would get `app/vendor/autoload.php` not found error. The problem has been fixed now, and the `app/vendor/autoload.php` created can then be copied over for the production readme generator during the step: `$LOCAL_COMPOSE build production_tool`.

2023-08-16 16:25 UTC, rija reviewed
Hi @kencho51, @pli888,

**praise**: I can run the script on my AWS live environment with `./createReadme.sh --doi 100142 --outdir /home/curators --wasabi --apply`
**praise**: The fix to the autoload issue is done in the right place
**issue**: Using my Rija role on Wasabi, when applying the `--use-live-data` I get permission denied error when rclone tries to write to the live directory even after I have switched role to Admin in Wasabi. Am I missing something?
**thought**: the way it's implemented, the current version of `postUpload.sh` would still work as it is, but I feel like the curators would appreciate greatly (will save them extra steps) if `postUpload.sh` is updated to upload the readme file directly to Wasabi

2023-08-17 03:37 UTC, kencho51 commented
Hi @rija,

> **issue**: Using my Rija role on Wasabi, when applying the `--use-live-data` I get permission denied error when rclone tries to write to the live directory even after I have switched role to Admin in Wasabi. Am I missing something?

Regarding this issue, I could upload `readme_100142.txt` from local to wasabi `/live/../100142` dir after login in as user `Ken` with role `Admin` assumed, otherwise will get access denied error. Also,  I could execute `$ ./createReadme.sh --doi 100142 --outdir /app/readmeFiles --wasabi --apply --use-live-data` in both my staging and live bastion servers and the log was: 
```
2023/08/17 03:11:43 INFO  : Created readme file in /home/centos/runtime/curators/readme_100142.txt
2023/08/17 03:11:43 INFO  : Copying readme file into LIVE data directory
2023/08/17 03:11:44 INFO  : readme_100142.txt: Copied (replaced existing)
2023/08/17 03:11:44 INFO  : Executed: rclone copy --s3-no-check-bucket /home/centos/readmeFiles/readme_100142.txt wasabi:gigadb-datasets/live/pub/10.5524/100001_101000/100142/ --config /home/centos/.config/rclone/rclone.conf ->
2023/08/17 03:11:44 INFO  : Successfully copied file to Wasabi for DOI: 100142
```

2023-08-24 19:55 UTC, rija approved these changes
Using the API keys for the Migration user like @pli888 did, I was able to get the script working with `--use-live-data`. For the purpose of readme migration, that's good enough.
updating of `postUpload.sh` and ensuring individual users can use it with the role switching will be looked into later on a separate PR.
So I'm happy to approve this PR

2023-08-25 05:38 UTC, pli888 approved these changes
The code looks good to me and I confirm I can copy readme_100142.txt into the gigadb-datasets/live directory.

2023-08-25 05:44 UTC, merged